title: Meu Site Jekyll
description: >
  Site baseado em Jekyll com navegação em single page.

banner_title: "Título do Site Aqui"
banner_subtitle: "Subtítulo explicativo do site"

colors:
  primary: "#114B5F"
  secondary: "#00AFB9"
  highlight: "#00AFB9"
  text: "#553A41"
  text_inverted: "#CEE1EB"
